feat: add optional proxy to cluster deletion call
This is for certain environments communicating via an HTTP proxy. It is optional as per values.yaml.

diff --git a/charts/rancher-cluster/templates/configmap.yaml b/charts/rancher-cluster/templates/configmap.yaml
--- a/charts/rancher-cluster/templates/configmap.yaml
+++ b/charts/rancher-cluster/templates/configmap.yaml
@@ -72,7 +72,7 @@ data:
             --request GET \
             --url "$RANCHERURL/v3/clusters?name=$CLUSTERNAME" \
             -u "$APITOKEN" | jq -r '.data[0].id')"
-        if [[ "$CLUSTER_ID" != 'null' ]]; then
+        if [[ "$CLUSTER_ID" != 'null' ]] && [[ -n "$CLUSTER_ID" ]]; then
             break
         elif [[ "$i" == '20' ]]; then
             echo "Could not get cluster ID for $CLUSTERNAME"
@@ -91,7 +91,7 @@ data:
             --request GET \
             --url "$RANCHERURL/v3/clusterregistrationtokens?clusterId=$CLUSTER_ID" \
             -u "$APITOKEN" | jq -r '.data[0].manifestUrl')"
-        if [[ "$AGENTURL" != 'null' ]]; then
+        if [[ "$AGENTURL" != 'null' ]] && [[ -n "$AGENTURL" ]]; then
             break
         elif [[ "$i" == '20' ]]; then
             echo "Could not get cluster registration token for $CLUSTERNAME ($CLUSTER_ID)"
@@ -135,20 +135,47 @@ data:
 
     echo "Successfully set up Vcluster as Rancher cluster"
   delete.sh: |
-    echo "CLUSTERNAME: $CLUSTERNAME"
-    while [ -z "$CLUSTERRESPONSE" ]; do
-      sleep 5
-      CLUSTERRESPONSE=`curl {{ $insecure }} -s "$RANCHERURL/v3/clusters?name=$CLUSTERNAME" -H 'content-type: application/json' -u "$APITOKEN"`
-      echo "CLUSTERRESPONSE: $CLUSTERRESPONSE"
+    echo "Removing cluster $CLUSTERNAME"
+
+    echo "Getting cluster ID for $CLUSTERNAME"
+    while :
+    do
+        CLUSTER_ID="$(curl {{ $insecure }} {{ $http_proxy }} \
+            --retry 5 --retry-delay 5 \
+            -sfL \
+            --request GET \
+            --url "$RANCHERURL/v3/clusters?name=$CLUSTERNAME" \
+            -u "$APITOKEN" | jq -r '.data[0].id')"
+        if [[ "$CLUSTER_ID" != 'null' ]] && [[ -n "$CLUSTER_ID" ]]; then
+            break
+        elif [[ "$i" == '20' ]]; then
+            echo "Could not get cluster ID for $CLUSTERNAME"
+            exit 1
+        fi
+        sleep 5
     done
-    CLUSTERID=`echo $CLUSTERRESPONSE | jq -r '.data[].id'`
-    echo "CLUSTERID: $CLUSTERID"
-    while [[ ! "$REMOVE" =~ "removing" ]]; do
-      sleep 5
-      REMOVE=`curl {{ $insecure }} -s -X DELETE "$RANCHERURL/v3/clusters/${CLUSTERID}" -H 'content-type: application/json' -u "$APITOKEN" |jq -r .state`
-      echo "REMOVE: $REMOVE"
+    echo "Got cluster ID ($CLUSTER_ID) for $CLUSTERNAME"
+
+    echo "Removing cluster with ID $CLUSTER_ID"
+    while :
+    do
+        RESULT="$(curl {{ $insecure }} {{ $http_proxy }} \
+            --retry 5 --retry-delay 5 \
+            -sfL \
+            --request DELETE \
+            --url "$RANCHERURL/v3/clusters/${CLUSTER_ID}" \
+            -u "$APITOKEN" | jq -r '.state')"
+        if [[ "$RESULT" != 'null' ]] && [[ -n "$RESULT" ]]; then
+            break
+        elif [[ "$i" == '20' ]]; then
+            echo "Could not remove cluster with ID $CLUSTER_ID"
+            exit 1
+        fi
+        sleep 5
     done
-    echo "CLUSTER REMOVED: $CLUSTERID"
+    echo "Removed cluster with ID $CLUSTER_ID (Result: $RESULT)"
+
+    echo "Successfully removed cluster $CLUSTERNAME"
 kind: ConfigMap
 metadata:
   labels:
